# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commons.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commons.proto',
  package='srv6_services',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rcommons.proto\x12\rsrv6_services*\xff\x02\n\nStatusCode\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12\"\n\x1eSTATUS_OPERATION_NOT_SUPPORTED\x10\x01\x12\x16\n\x12STATUS_BAD_REQUEST\x10\x02\x12\x19\n\x15STATUS_INTERNAL_ERROR\x10\x03\x12\x1f\n\x1bSTATUS_INVALID_GRPC_REQUEST\x10\x04\x12\x16\n\x12STATUS_FILE_EXISTS\x10\x05\x12\x1a\n\x16STATUS_NO_SUCH_PROCESS\x10\x06\x12\x19\n\x15STATUS_INVALID_ACTION\x10\x07\x12#\n\x1fSTATUS_GRPC_SERVICE_UNAVAILABLE\x10\x08\x12\x1c\n\x18STATUS_GRPC_UNAUTHORIZED\x10\t\x12\x19\n\x15STATUS_NOT_CONFIGURED\x10\n\x12\x1d\n\x19STATUS_ALREADY_CONFIGURED\x10\x0b\x12\x19\n\x15STATUS_NO_SUCH_DEVICE\x10\x0c\x62\x06proto3'
)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='srv6_services.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_OPERATION_NOT_SUPPORTED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_BAD_REQUEST', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_INTERNAL_ERROR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_INVALID_GRPC_REQUEST', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_FILE_EXISTS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_NO_SUCH_PROCESS', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_INVALID_ACTION', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_GRPC_SERVICE_UNAVAILABLE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_GRPC_UNAUTHORIZED', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_NOT_CONFIGURED', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_ALREADY_CONFIGURED', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_NO_SUCH_DEVICE', index=12, number=12,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=33,
  serialized_end=416,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
STATUS_SUCCESS = 0
STATUS_OPERATION_NOT_SUPPORTED = 1
STATUS_BAD_REQUEST = 2
STATUS_INTERNAL_ERROR = 3
STATUS_INVALID_GRPC_REQUEST = 4
STATUS_FILE_EXISTS = 5
STATUS_NO_SUCH_PROCESS = 6
STATUS_INVALID_ACTION = 7
STATUS_GRPC_SERVICE_UNAVAILABLE = 8
STATUS_GRPC_UNAUTHORIZED = 9
STATUS_NOT_CONFIGURED = 10
STATUS_ALREADY_CONFIGURED = 11
STATUS_NO_SUCH_DEVICE = 12


DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
