# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import srv6pmCommons_pb2 as srv6pmCommons__pb2
import srv6pmReflector_pb2 as srv6pmReflector__pb2


class SRv6PMReflectorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.startExperiment = channel.unary_unary(
                '/srv6pm.SRv6PMReflector/startExperiment',
                request_serializer=srv6pmReflector__pb2.StartExperimentReflectorRequest.SerializeToString,
                response_deserializer=srv6pmReflector__pb2.StartExperimentReflectorReply.FromString,
                )
        self.stopExperiment = channel.unary_unary(
                '/srv6pm.SRv6PMReflector/stopExperiment',
                request_serializer=srv6pmCommons__pb2.StopExperimentRequest.SerializeToString,
                response_deserializer=srv6pmCommons__pb2.StopExperimentReply.FromString,
                )
        self.retriveExperimentResults = channel.unary_unary(
                '/srv6pm.SRv6PMReflector/retriveExperimentResults',
                request_serializer=srv6pmCommons__pb2.RetriveExperimentDataRequest.SerializeToString,
                response_deserializer=srv6pmCommons__pb2.ExperimentDataResponse.FromString,
                )
        self.CreateSRv6TunnelReflector = channel.unary_unary(
                '/srv6pm.SRv6PMReflector/CreateSRv6TunnelReflector',
                request_serializer=srv6pmReflector__pb2.SRv6EPRequestReflector.SerializeToString,
                response_deserializer=srv6pmReflector__pb2.SRv6EPReplyReflector.FromString,
                )


class SRv6PMReflectorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def startExperiment(self, request, context):
        """start an experiment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopExperiment(self, request, context):
        """stop am experiment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def retriveExperimentResults(self, request, context):
        """retrive data of an experiment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSRv6TunnelReflector(self, request, context):
        """Tunnel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SRv6PMReflectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'startExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.startExperiment,
                    request_deserializer=srv6pmReflector__pb2.StartExperimentReflectorRequest.FromString,
                    response_serializer=srv6pmReflector__pb2.StartExperimentReflectorReply.SerializeToString,
            ),
            'stopExperiment': grpc.unary_unary_rpc_method_handler(
                    servicer.stopExperiment,
                    request_deserializer=srv6pmCommons__pb2.StopExperimentRequest.FromString,
                    response_serializer=srv6pmCommons__pb2.StopExperimentReply.SerializeToString,
            ),
            'retriveExperimentResults': grpc.unary_unary_rpc_method_handler(
                    servicer.retriveExperimentResults,
                    request_deserializer=srv6pmCommons__pb2.RetriveExperimentDataRequest.FromString,
                    response_serializer=srv6pmCommons__pb2.ExperimentDataResponse.SerializeToString,
            ),
            'CreateSRv6TunnelReflector': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSRv6TunnelReflector,
                    request_deserializer=srv6pmReflector__pb2.SRv6EPRequestReflector.FromString,
                    response_serializer=srv6pmReflector__pb2.SRv6EPReplyReflector.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'srv6pm.SRv6PMReflector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SRv6PMReflector(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def startExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.SRv6PMReflector/startExperiment',
            srv6pmReflector__pb2.StartExperimentReflectorRequest.SerializeToString,
            srv6pmReflector__pb2.StartExperimentReflectorReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopExperiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.SRv6PMReflector/stopExperiment',
            srv6pmCommons__pb2.StopExperimentRequest.SerializeToString,
            srv6pmCommons__pb2.StopExperimentReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def retriveExperimentResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.SRv6PMReflector/retriveExperimentResults',
            srv6pmCommons__pb2.RetriveExperimentDataRequest.SerializeToString,
            srv6pmCommons__pb2.ExperimentDataResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSRv6TunnelReflector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6pm.SRv6PMReflector/CreateSRv6TunnelReflector',
            srv6pmReflector__pb2.SRv6EPRequestReflector.SerializeToString,
            srv6pmReflector__pb2.SRv6EPReplyReflector.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
