# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv6pmService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import srv6pmCommons_pb2 as srv6pmCommons__pb2
import srv6pmSender_pb2 as srv6pmSender__pb2
import srv6pmReflector_pb2 as srv6pmReflector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='srv6pmService.proto',
  package='srv6pm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13srv6pmService.proto\x12\x06srv6pm\x1a\x13srv6pmCommons.proto\x1a\x12srv6pmSender.proto\x1a\x15srv6pmReflector.proto2\x88\x05\n\x06SRv6PM\x12J\n\x10setConfiguration\x12\x15.srv6pm.Configuration\x1a\x1d.srv6pm.SetConfigurationReply\"\x00\x12L\n\x12resetConfiguration\x12\x15.srv6pm.Configuration\x1a\x1d.srv6pm.SetConfigurationReply\"\x00\x12\x63\n\x15startExperimentSender\x12$.srv6pm.StartExperimentSenderRequest\x1a\".srv6pm.StartExperimentSenderReply\"\x00\x12l\n\x18startExperimentReflector\x12\'.srv6pm.StartExperimentReflectorRequest\x1a%.srv6pm.StartExperimentReflectorReply\"\x00\x12T\n\x14stopExperimentSender\x12\x1d.srv6pm.StopExperimentRequest\x1a\x1b.srv6pm.StopExperimentReply\"\x00\x12W\n\x17stopExperimentReflector\x12\x1d.srv6pm.StopExperimentRequest\x1a\x1b.srv6pm.StopExperimentReply\"\x00\x12\x62\n\x18retriveExperimentResults\x12$.srv6pm.RetriveExperimentDataRequest\x1a\x1e.srv6pm.ExperimentDataResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[srv6pmCommons__pb2.DESCRIPTOR,srv6pmSender__pb2.DESCRIPTOR,srv6pmReflector__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SRV6PM = _descriptor.ServiceDescriptor(
  name='SRv6PM',
  full_name='srv6pm.SRv6PM',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=96,
  serialized_end=744,
  methods=[
  _descriptor.MethodDescriptor(
    name='setConfiguration',
    full_name='srv6pm.SRv6PM.setConfiguration',
    index=0,
    containing_service=None,
    input_type=srv6pmCommons__pb2._CONFIGURATION,
    output_type=srv6pmCommons__pb2._SETCONFIGURATIONREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='resetConfiguration',
    full_name='srv6pm.SRv6PM.resetConfiguration',
    index=1,
    containing_service=None,
    input_type=srv6pmCommons__pb2._CONFIGURATION,
    output_type=srv6pmCommons__pb2._SETCONFIGURATIONREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='startExperimentSender',
    full_name='srv6pm.SRv6PM.startExperimentSender',
    index=2,
    containing_service=None,
    input_type=srv6pmSender__pb2._STARTEXPERIMENTSENDERREQUEST,
    output_type=srv6pmSender__pb2._STARTEXPERIMENTSENDERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='startExperimentReflector',
    full_name='srv6pm.SRv6PM.startExperimentReflector',
    index=3,
    containing_service=None,
    input_type=srv6pmReflector__pb2._STARTEXPERIMENTREFLECTORREQUEST,
    output_type=srv6pmReflector__pb2._STARTEXPERIMENTREFLECTORREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopExperimentSender',
    full_name='srv6pm.SRv6PM.stopExperimentSender',
    index=4,
    containing_service=None,
    input_type=srv6pmCommons__pb2._STOPEXPERIMENTREQUEST,
    output_type=srv6pmCommons__pb2._STOPEXPERIMENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopExperimentReflector',
    full_name='srv6pm.SRv6PM.stopExperimentReflector',
    index=5,
    containing_service=None,
    input_type=srv6pmCommons__pb2._STOPEXPERIMENTREQUEST,
    output_type=srv6pmCommons__pb2._STOPEXPERIMENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='retriveExperimentResults',
    full_name='srv6pm.SRv6PM.retriveExperimentResults',
    index=6,
    containing_service=None,
    input_type=srv6pmCommons__pb2._RETRIVEEXPERIMENTDATAREQUEST,
    output_type=srv6pmCommons__pb2._EXPERIMENTDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SRV6PM)

DESCRIPTOR.services_by_name['SRv6PM'] = _SRV6PM

# @@protoc_insertion_point(module_scope)
