# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv6pmServiceController.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import srv6pmCommons_pb2 as srv6pmCommons__pb2
import commons_pb2 as commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='srv6pmServiceController.proto',
  package='srv6pm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1dsrv6pmServiceController.proto\x12\x06srv6pm\x1a\x13srv6pmCommons.proto\x1a\rcommons.proto\"O\n\x1aSendMeasurementDataRequest\x12\x31\n\x10measurement_data\x18\x01 \x03(\x0b\x32\x17.srv6pm.MeasurementData\"H\n\x1bSendMeasurementDataResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.srv6_services.StatusCode\"\x17\n\x08Interval\x12\x0b\n\x03val\x18\x01 \x01(\t\"#\n\x07\x42itrate\x12\x0b\n\x03val\x18\x01 \x01(\x02\x12\x0b\n\x03\x64im\x18\x02 \x01(\t\"$\n\x08Transfer\x12\x0b\n\x03val\x18\x01 \x01(\x02\x12\x0b\n\x03\x64im\x18\x02 \x01(\t\"\x13\n\x04Retr\x12\x0b\n\x03val\x18\x01 \x01(\r\" \n\x04\x43wnd\x12\x0b\n\x03val\x18\x01 \x01(\x02\x12\x0b\n\x03\x64im\x18\x02 \x01(\t\"\xe6\x01\n\tIperfData\x12\r\n\x05_from\x18\x01 \x01(\t\x12\x12\n\nmeasure_id\x18\x02 \x01(\r\x12\x14\n\x0cgenerator_id\x18\x03 \x01(\r\x12\"\n\x08interval\x18\x04 \x01(\x0b\x32\x10.srv6pm.Interval\x12 \n\x07\x62itrate\x18\x05 \x01(\x0b\x32\x0f.srv6pm.Bitrate\x12\"\n\x08transfer\x18\x06 \x01(\x0b\x32\x10.srv6pm.Transfer\x12\x1a\n\x04retr\x18\x07 \x01(\x0b\x32\x0c.srv6pm.Retr\x12\x1a\n\x04\x63wnd\x18\x08 \x01(\x0b\x32\x0c.srv6pm.Cwnd\"=\n\x14SendIperfDataRequest\x12%\n\niperf_data\x18\x01 \x03(\x0b\x32\x11.srv6pm.IperfData\"B\n\x15SendIperfDataResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.srv6_services.StatusCode2\xc4\x01\n\x10SRv6PMController\x12`\n\x13SendMeasurementData\x12\".srv6pm.SendMeasurementDataRequest\x1a#.srv6pm.SendMeasurementDataResponse\"\x00\x12N\n\rSendIperfData\x12\x1c.srv6pm.SendIperfDataRequest\x1a\x1d.srv6pm.SendIperfDataResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[srv6pmCommons__pb2.DESCRIPTOR,commons__pb2.DESCRIPTOR,])




_SENDMEASUREMENTDATAREQUEST = _descriptor.Descriptor(
  name='SendMeasurementDataRequest',
  full_name='srv6pm.SendMeasurementDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurement_data', full_name='srv6pm.SendMeasurementDataRequest.measurement_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=156,
)


_SENDMEASUREMENTDATARESPONSE = _descriptor.Descriptor(
  name='SendMeasurementDataResponse',
  full_name='srv6pm.SendMeasurementDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='srv6pm.SendMeasurementDataResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=230,
)


_INTERVAL = _descriptor.Descriptor(
  name='Interval',
  full_name='srv6pm.Interval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='srv6pm.Interval.val', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=255,
)


_BITRATE = _descriptor.Descriptor(
  name='Bitrate',
  full_name='srv6pm.Bitrate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='srv6pm.Bitrate.val', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dim', full_name='srv6pm.Bitrate.dim', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=292,
)


_TRANSFER = _descriptor.Descriptor(
  name='Transfer',
  full_name='srv6pm.Transfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='srv6pm.Transfer.val', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dim', full_name='srv6pm.Transfer.dim', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=330,
)


_RETR = _descriptor.Descriptor(
  name='Retr',
  full_name='srv6pm.Retr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='srv6pm.Retr.val', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=351,
)


_CWND = _descriptor.Descriptor(
  name='Cwnd',
  full_name='srv6pm.Cwnd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='srv6pm.Cwnd.val', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dim', full_name='srv6pm.Cwnd.dim', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=385,
)


_IPERFDATA = _descriptor.Descriptor(
  name='IperfData',
  full_name='srv6pm.IperfData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_from', full_name='srv6pm.IperfData._from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measure_id', full_name='srv6pm.IperfData.measure_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generator_id', full_name='srv6pm.IperfData.generator_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval', full_name='srv6pm.IperfData.interval', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bitrate', full_name='srv6pm.IperfData.bitrate', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transfer', full_name='srv6pm.IperfData.transfer', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retr', full_name='srv6pm.IperfData.retr', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cwnd', full_name='srv6pm.IperfData.cwnd', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=618,
)


_SENDIPERFDATAREQUEST = _descriptor.Descriptor(
  name='SendIperfDataRequest',
  full_name='srv6pm.SendIperfDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iperf_data', full_name='srv6pm.SendIperfDataRequest.iperf_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=681,
)


_SENDIPERFDATARESPONSE = _descriptor.Descriptor(
  name='SendIperfDataResponse',
  full_name='srv6pm.SendIperfDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='srv6pm.SendIperfDataResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=683,
  serialized_end=749,
)

_SENDMEASUREMENTDATAREQUEST.fields_by_name['measurement_data'].message_type = srv6pmCommons__pb2._MEASUREMENTDATA
_SENDMEASUREMENTDATARESPONSE.fields_by_name['status'].enum_type = commons__pb2._STATUSCODE
_IPERFDATA.fields_by_name['interval'].message_type = _INTERVAL
_IPERFDATA.fields_by_name['bitrate'].message_type = _BITRATE
_IPERFDATA.fields_by_name['transfer'].message_type = _TRANSFER
_IPERFDATA.fields_by_name['retr'].message_type = _RETR
_IPERFDATA.fields_by_name['cwnd'].message_type = _CWND
_SENDIPERFDATAREQUEST.fields_by_name['iperf_data'].message_type = _IPERFDATA
_SENDIPERFDATARESPONSE.fields_by_name['status'].enum_type = commons__pb2._STATUSCODE
DESCRIPTOR.message_types_by_name['SendMeasurementDataRequest'] = _SENDMEASUREMENTDATAREQUEST
DESCRIPTOR.message_types_by_name['SendMeasurementDataResponse'] = _SENDMEASUREMENTDATARESPONSE
DESCRIPTOR.message_types_by_name['Interval'] = _INTERVAL
DESCRIPTOR.message_types_by_name['Bitrate'] = _BITRATE
DESCRIPTOR.message_types_by_name['Transfer'] = _TRANSFER
DESCRIPTOR.message_types_by_name['Retr'] = _RETR
DESCRIPTOR.message_types_by_name['Cwnd'] = _CWND
DESCRIPTOR.message_types_by_name['IperfData'] = _IPERFDATA
DESCRIPTOR.message_types_by_name['SendIperfDataRequest'] = _SENDIPERFDATAREQUEST
DESCRIPTOR.message_types_by_name['SendIperfDataResponse'] = _SENDIPERFDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendMeasurementDataRequest = _reflection.GeneratedProtocolMessageType('SendMeasurementDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDMEASUREMENTDATAREQUEST,
  '__module__' : 'srv6pmServiceController_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.SendMeasurementDataRequest)
  })
_sym_db.RegisterMessage(SendMeasurementDataRequest)

SendMeasurementDataResponse = _reflection.GeneratedProtocolMessageType('SendMeasurementDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDMEASUREMENTDATARESPONSE,
  '__module__' : 'srv6pmServiceController_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.SendMeasurementDataResponse)
  })
_sym_db.RegisterMessage(SendMeasurementDataResponse)

Interval = _reflection.GeneratedProtocolMessageType('Interval', (_message.Message,), {
  'DESCRIPTOR' : _INTERVAL,
  '__module__' : 'srv6pmServiceController_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.Interval)
  })
_sym_db.RegisterMessage(Interval)

Bitrate = _reflection.GeneratedProtocolMessageType('Bitrate', (_message.Message,), {
  'DESCRIPTOR' : _BITRATE,
  '__module__' : 'srv6pmServiceController_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.Bitrate)
  })
_sym_db.RegisterMessage(Bitrate)

Transfer = _reflection.GeneratedProtocolMessageType('Transfer', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFER,
  '__module__' : 'srv6pmServiceController_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.Transfer)
  })
_sym_db.RegisterMessage(Transfer)

Retr = _reflection.GeneratedProtocolMessageType('Retr', (_message.Message,), {
  'DESCRIPTOR' : _RETR,
  '__module__' : 'srv6pmServiceController_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.Retr)
  })
_sym_db.RegisterMessage(Retr)

Cwnd = _reflection.GeneratedProtocolMessageType('Cwnd', (_message.Message,), {
  'DESCRIPTOR' : _CWND,
  '__module__' : 'srv6pmServiceController_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.Cwnd)
  })
_sym_db.RegisterMessage(Cwnd)

IperfData = _reflection.GeneratedProtocolMessageType('IperfData', (_message.Message,), {
  'DESCRIPTOR' : _IPERFDATA,
  '__module__' : 'srv6pmServiceController_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.IperfData)
  })
_sym_db.RegisterMessage(IperfData)

SendIperfDataRequest = _reflection.GeneratedProtocolMessageType('SendIperfDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDIPERFDATAREQUEST,
  '__module__' : 'srv6pmServiceController_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.SendIperfDataRequest)
  })
_sym_db.RegisterMessage(SendIperfDataRequest)

SendIperfDataResponse = _reflection.GeneratedProtocolMessageType('SendIperfDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDIPERFDATARESPONSE,
  '__module__' : 'srv6pmServiceController_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.SendIperfDataResponse)
  })
_sym_db.RegisterMessage(SendIperfDataResponse)



_SRV6PMCONTROLLER = _descriptor.ServiceDescriptor(
  name='SRv6PMController',
  full_name='srv6pm.SRv6PMController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=752,
  serialized_end=948,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMeasurementData',
    full_name='srv6pm.SRv6PMController.SendMeasurementData',
    index=0,
    containing_service=None,
    input_type=_SENDMEASUREMENTDATAREQUEST,
    output_type=_SENDMEASUREMENTDATARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendIperfData',
    full_name='srv6pm.SRv6PMController.SendIperfData',
    index=1,
    containing_service=None,
    input_type=_SENDIPERFDATAREQUEST,
    output_type=_SENDIPERFDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SRV6PMCONTROLLER)

DESCRIPTOR.services_by_name['SRv6PMController'] = _SRV6PMCONTROLLER

# @@protoc_insertion_point(module_scope)
