# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import srv6_manager_pb2 as srv6__manager__pb2


class SRv6ManagerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/srv6_manager.SRv6Manager/Create',
                request_serializer=srv6__manager__pb2.SRv6ManagerRequest.SerializeToString,
                response_deserializer=srv6__manager__pb2.SRv6ManagerReply.FromString,
                )
        self.Get = channel.unary_unary(
                '/srv6_manager.SRv6Manager/Get',
                request_serializer=srv6__manager__pb2.SRv6ManagerRequest.SerializeToString,
                response_deserializer=srv6__manager__pb2.SRv6ManagerReply.FromString,
                )
        self.Update = channel.unary_unary(
                '/srv6_manager.SRv6Manager/Update',
                request_serializer=srv6__manager__pb2.SRv6ManagerRequest.SerializeToString,
                response_deserializer=srv6__manager__pb2.SRv6ManagerReply.FromString,
                )
        self.Remove = channel.unary_unary(
                '/srv6_manager.SRv6Manager/Remove',
                request_serializer=srv6__manager__pb2.SRv6ManagerRequest.SerializeToString,
                response_deserializer=srv6__manager__pb2.SRv6ManagerReply.FromString,
                )


class SRv6ManagerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Create(self, request, context):
        """Create operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Get operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Update operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Remove operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SRv6ManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=srv6__manager__pb2.SRv6ManagerRequest.FromString,
                    response_serializer=srv6__manager__pb2.SRv6ManagerReply.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=srv6__manager__pb2.SRv6ManagerRequest.FromString,
                    response_serializer=srv6__manager__pb2.SRv6ManagerReply.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=srv6__manager__pb2.SRv6ManagerRequest.FromString,
                    response_serializer=srv6__manager__pb2.SRv6ManagerReply.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=srv6__manager__pb2.SRv6ManagerRequest.FromString,
                    response_serializer=srv6__manager__pb2.SRv6ManagerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'srv6_manager.SRv6Manager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SRv6Manager(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6_manager.SRv6Manager/Create',
            srv6__manager__pb2.SRv6ManagerRequest.SerializeToString,
            srv6__manager__pb2.SRv6ManagerReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6_manager.SRv6Manager/Get',
            srv6__manager__pb2.SRv6ManagerRequest.SerializeToString,
            srv6__manager__pb2.SRv6ManagerReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6_manager.SRv6Manager/Update',
            srv6__manager__pb2.SRv6ManagerRequest.SerializeToString,
            srv6__manager__pb2.SRv6ManagerReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srv6_manager.SRv6Manager/Remove',
            srv6__manager__pb2.SRv6ManagerRequest.SerializeToString,
            srv6__manager__pb2.SRv6ManagerReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
