# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv6pmReflector.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import srv6pmCommons_pb2 as srv6pmCommons__pb2
import commons_pb2 as commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='srv6pmReflector.proto',
  package='srv6pm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15srv6pmReflector.proto\x12\x06srv6pm\x1a\x13srv6pmCommons.proto\x1a\rcommons.proto\"]\n\x16SRv6EPRequestReflector\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\x11\n\tencapmode\x18\x02 \x01(\t\x12\x10\n\x08segments\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\"B\n\x14SRv6EPReplyReflector\x12*\n\x06status\x18\xc8\x01 \x01(\x0e\x32\x19.srv6_services.StatusCode\"\x91\x01\n\x1fStartExperimentReflectorRequest\x12\x12\n\nmeasure_id\x18\x01 \x01(\r\x12\x0e\n\x06sdlist\x18\x02 \x01(\t\x12\x15\n\rsdlistreverse\x18\x03 \x01(\t\x12\x33\n\x11reflector_options\x18\x04 \x01(\x0b\x32\x18.srv6pm.ReflectorOptions\"J\n\x1dStartExperimentReflectorReply\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.srv6_services.StatusCode\"\x91\x02\n\x10ReflectorOptions\x12\x39\n\x14measurement_protocol\x18\x03 \x01(\x0e\x32\x1b.srv6pm.MeasurementProtocol\x12\x37\n\x13\x61uthentication_mode\x18\x04 \x01(\x0e\x32\x1a.srv6pm.AuthenticationMode\x12\x31\n\x10measurement_type\x18\x05 \x01(\x0e\x32\x17.srv6pm.MeasurementType\x12:\n\x15measurement_loss_mode\x18\x06 \x01(\x0e\x32\x1b.srv6pm.MeasurementLossMode\x12\x1a\n\x12\x61uthentication_key\x18\x07 \x01(\t2\x87\x03\n\x0fSRv6PMReflector\x12\x63\n\x0fstartExperiment\x12\'.srv6pm.StartExperimentReflectorRequest\x1a%.srv6pm.StartExperimentReflectorReply\"\x00\x12N\n\x0estopExperiment\x12\x1d.srv6pm.StopExperimentRequest\x1a\x1b.srv6pm.StopExperimentReply\"\x00\x12\x62\n\x18retriveExperimentResults\x12$.srv6pm.RetriveExperimentDataRequest\x1a\x1e.srv6pm.ExperimentDataResponse\"\x00\x12[\n\x19\x43reateSRv6TunnelReflector\x12\x1e.srv6pm.SRv6EPRequestReflector\x1a\x1c.srv6pm.SRv6EPReplyReflector\"\x00\x62\x06proto3'
  ,
  dependencies=[srv6pmCommons__pb2.DESCRIPTOR,commons__pb2.DESCRIPTOR,])




_SRV6EPREQUESTREFLECTOR = _descriptor.Descriptor(
  name='SRv6EPRequestReflector',
  full_name='srv6pm.SRv6EPRequestReflector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefix', full_name='srv6pm.SRv6EPRequestReflector.prefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encapmode', full_name='srv6pm.SRv6EPRequestReflector.encapmode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segments', full_name='srv6pm.SRv6EPRequestReflector.segments', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device', full_name='srv6pm.SRv6EPRequestReflector.device', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=162,
)


_SRV6EPREPLYREFLECTOR = _descriptor.Descriptor(
  name='SRv6EPReplyReflector',
  full_name='srv6pm.SRv6EPReplyReflector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='srv6pm.SRv6EPReplyReflector.status', index=0,
      number=200, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=230,
)


_STARTEXPERIMENTREFLECTORREQUEST = _descriptor.Descriptor(
  name='StartExperimentReflectorRequest',
  full_name='srv6pm.StartExperimentReflectorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measure_id', full_name='srv6pm.StartExperimentReflectorRequest.measure_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sdlist', full_name='srv6pm.StartExperimentReflectorRequest.sdlist', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sdlistreverse', full_name='srv6pm.StartExperimentReflectorRequest.sdlistreverse', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reflector_options', full_name='srv6pm.StartExperimentReflectorRequest.reflector_options', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=378,
)


_STARTEXPERIMENTREFLECTORREPLY = _descriptor.Descriptor(
  name='StartExperimentReflectorReply',
  full_name='srv6pm.StartExperimentReflectorReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='srv6pm.StartExperimentReflectorReply.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=454,
)


_REFLECTOROPTIONS = _descriptor.Descriptor(
  name='ReflectorOptions',
  full_name='srv6pm.ReflectorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurement_protocol', full_name='srv6pm.ReflectorOptions.measurement_protocol', index=0,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authentication_mode', full_name='srv6pm.ReflectorOptions.authentication_mode', index=1,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurement_type', full_name='srv6pm.ReflectorOptions.measurement_type', index=2,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurement_loss_mode', full_name='srv6pm.ReflectorOptions.measurement_loss_mode', index=3,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authentication_key', full_name='srv6pm.ReflectorOptions.authentication_key', index=4,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=730,
)

_SRV6EPREPLYREFLECTOR.fields_by_name['status'].enum_type = commons__pb2._STATUSCODE
_STARTEXPERIMENTREFLECTORREQUEST.fields_by_name['reflector_options'].message_type = _REFLECTOROPTIONS
_STARTEXPERIMENTREFLECTORREPLY.fields_by_name['status'].enum_type = commons__pb2._STATUSCODE
_REFLECTOROPTIONS.fields_by_name['measurement_protocol'].enum_type = srv6pmCommons__pb2._MEASUREMENTPROTOCOL
_REFLECTOROPTIONS.fields_by_name['authentication_mode'].enum_type = srv6pmCommons__pb2._AUTHENTICATIONMODE
_REFLECTOROPTIONS.fields_by_name['measurement_type'].enum_type = srv6pmCommons__pb2._MEASUREMENTTYPE
_REFLECTOROPTIONS.fields_by_name['measurement_loss_mode'].enum_type = srv6pmCommons__pb2._MEASUREMENTLOSSMODE
DESCRIPTOR.message_types_by_name['SRv6EPRequestReflector'] = _SRV6EPREQUESTREFLECTOR
DESCRIPTOR.message_types_by_name['SRv6EPReplyReflector'] = _SRV6EPREPLYREFLECTOR
DESCRIPTOR.message_types_by_name['StartExperimentReflectorRequest'] = _STARTEXPERIMENTREFLECTORREQUEST
DESCRIPTOR.message_types_by_name['StartExperimentReflectorReply'] = _STARTEXPERIMENTREFLECTORREPLY
DESCRIPTOR.message_types_by_name['ReflectorOptions'] = _REFLECTOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SRv6EPRequestReflector = _reflection.GeneratedProtocolMessageType('SRv6EPRequestReflector', (_message.Message,), {
  'DESCRIPTOR' : _SRV6EPREQUESTREFLECTOR,
  '__module__' : 'srv6pmReflector_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.SRv6EPRequestReflector)
  })
_sym_db.RegisterMessage(SRv6EPRequestReflector)

SRv6EPReplyReflector = _reflection.GeneratedProtocolMessageType('SRv6EPReplyReflector', (_message.Message,), {
  'DESCRIPTOR' : _SRV6EPREPLYREFLECTOR,
  '__module__' : 'srv6pmReflector_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.SRv6EPReplyReflector)
  })
_sym_db.RegisterMessage(SRv6EPReplyReflector)

StartExperimentReflectorRequest = _reflection.GeneratedProtocolMessageType('StartExperimentReflectorRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTEXPERIMENTREFLECTORREQUEST,
  '__module__' : 'srv6pmReflector_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.StartExperimentReflectorRequest)
  })
_sym_db.RegisterMessage(StartExperimentReflectorRequest)

StartExperimentReflectorReply = _reflection.GeneratedProtocolMessageType('StartExperimentReflectorReply', (_message.Message,), {
  'DESCRIPTOR' : _STARTEXPERIMENTREFLECTORREPLY,
  '__module__' : 'srv6pmReflector_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.StartExperimentReflectorReply)
  })
_sym_db.RegisterMessage(StartExperimentReflectorReply)

ReflectorOptions = _reflection.GeneratedProtocolMessageType('ReflectorOptions', (_message.Message,), {
  'DESCRIPTOR' : _REFLECTOROPTIONS,
  '__module__' : 'srv6pmReflector_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.ReflectorOptions)
  })
_sym_db.RegisterMessage(ReflectorOptions)



_SRV6PMREFLECTOR = _descriptor.ServiceDescriptor(
  name='SRv6PMReflector',
  full_name='srv6pm.SRv6PMReflector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=733,
  serialized_end=1124,
  methods=[
  _descriptor.MethodDescriptor(
    name='startExperiment',
    full_name='srv6pm.SRv6PMReflector.startExperiment',
    index=0,
    containing_service=None,
    input_type=_STARTEXPERIMENTREFLECTORREQUEST,
    output_type=_STARTEXPERIMENTREFLECTORREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopExperiment',
    full_name='srv6pm.SRv6PMReflector.stopExperiment',
    index=1,
    containing_service=None,
    input_type=srv6pmCommons__pb2._STOPEXPERIMENTREQUEST,
    output_type=srv6pmCommons__pb2._STOPEXPERIMENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='retriveExperimentResults',
    full_name='srv6pm.SRv6PMReflector.retriveExperimentResults',
    index=2,
    containing_service=None,
    input_type=srv6pmCommons__pb2._RETRIVEEXPERIMENTDATAREQUEST,
    output_type=srv6pmCommons__pb2._EXPERIMENTDATARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateSRv6TunnelReflector',
    full_name='srv6pm.SRv6PMReflector.CreateSRv6TunnelReflector',
    index=3,
    containing_service=None,
    input_type=_SRV6EPREQUESTREFLECTOR,
    output_type=_SRV6EPREPLYREFLECTOR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SRV6PMREFLECTOR)

DESCRIPTOR.services_by_name['SRv6PMReflector'] = _SRV6PMREFLECTOR

# @@protoc_insertion_point(module_scope)
