# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv6pmSender.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import srv6pmCommons_pb2 as srv6pmCommons__pb2
import commons_pb2 as commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='srv6pmSender.proto',
  package='srv6pm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12srv6pmSender.proto\x12\x06srv6pm\x1a\x13srv6pmCommons.proto\x1a\rcommons.proto\"Z\n\x13SRv6EPRequestSender\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\x11\n\tencapmode\x18\x02 \x01(\t\x12\x10\n\x08segments\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\"?\n\x11SRv6EPReplySender\x12*\n\x06status\x18\xfa\x01 \x01(\x0e\x32\x19.srv6_services.StatusCode\"\x88\x01\n\x1cStartExperimentSenderRequest\x12\x12\n\nmeasure_id\x18\x01 \x01(\r\x12\x0e\n\x06sdlist\x18\x02 \x01(\t\x12\x15\n\rsdlistreverse\x18\x03 \x01(\t\x12-\n\x0esender_options\x18\x04 \x01(\x0b\x32\x15.srv6pm.SenderOptions\"G\n\x1aStartExperimentSenderReply\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.srv6_services.StatusCode\"\x94\x03\n\rSenderOptions\x12\x39\n\x14measurement_protocol\x18\x03 \x01(\x0e\x32\x1b.srv6pm.MeasurementProtocol\x12\x37\n\x13\x61uthentication_mode\x18\x04 \x01(\x0e\x32\x1a.srv6pm.AuthenticationMode\x12\x31\n\x10measurement_type\x18\x05 \x01(\x0e\x32\x17.srv6pm.MeasurementType\x12\x31\n\x10timestamp_format\x18\x06 \x01(\x0e\x32\x17.srv6pm.TimestampFormat\x12<\n\x16measurement_delay_mode\x18\x07 \x01(\x0e\x32\x1c.srv6pm.MeasurementDelayMode\x12\x13\n\x0bpadding_mbz\x18\x08 \x01(\r\x12:\n\x15measurement_loss_mode\x18\t \x01(\x0e\x32\x1b.srv6pm.MeasurementLossMode\x12\x1a\n\x12\x61uthentication_key\x18\n \x01(\t2\xa1\x02\n\x0cSRv6PMSender\x12]\n\x0fstartExperiment\x12$.srv6pm.StartExperimentSenderRequest\x1a\".srv6pm.StartExperimentSenderReply\"\x00\x12N\n\x0estopExperiment\x12\x1d.srv6pm.StopExperimentRequest\x1a\x1b.srv6pm.StopExperimentReply\"\x00\x12\x62\n\x18retriveExperimentResults\x12$.srv6pm.RetriveExperimentDataRequest\x1a\x1e.srv6pm.ExperimentDataResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[srv6pmCommons__pb2.DESCRIPTOR,commons__pb2.DESCRIPTOR,])




_SRV6EPREQUESTSENDER = _descriptor.Descriptor(
  name='SRv6EPRequestSender',
  full_name='srv6pm.SRv6EPRequestSender',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefix', full_name='srv6pm.SRv6EPRequestSender.prefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encapmode', full_name='srv6pm.SRv6EPRequestSender.encapmode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segments', full_name='srv6pm.SRv6EPRequestSender.segments', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device', full_name='srv6pm.SRv6EPRequestSender.device', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=156,
)


_SRV6EPREPLYSENDER = _descriptor.Descriptor(
  name='SRv6EPReplySender',
  full_name='srv6pm.SRv6EPReplySender',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='srv6pm.SRv6EPReplySender.status', index=0,
      number=250, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=221,
)


_STARTEXPERIMENTSENDERREQUEST = _descriptor.Descriptor(
  name='StartExperimentSenderRequest',
  full_name='srv6pm.StartExperimentSenderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measure_id', full_name='srv6pm.StartExperimentSenderRequest.measure_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sdlist', full_name='srv6pm.StartExperimentSenderRequest.sdlist', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sdlistreverse', full_name='srv6pm.StartExperimentSenderRequest.sdlistreverse', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender_options', full_name='srv6pm.StartExperimentSenderRequest.sender_options', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=360,
)


_STARTEXPERIMENTSENDERREPLY = _descriptor.Descriptor(
  name='StartExperimentSenderReply',
  full_name='srv6pm.StartExperimentSenderReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='srv6pm.StartExperimentSenderReply.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=433,
)


_SENDEROPTIONS = _descriptor.Descriptor(
  name='SenderOptions',
  full_name='srv6pm.SenderOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measurement_protocol', full_name='srv6pm.SenderOptions.measurement_protocol', index=0,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authentication_mode', full_name='srv6pm.SenderOptions.authentication_mode', index=1,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurement_type', full_name='srv6pm.SenderOptions.measurement_type', index=2,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_format', full_name='srv6pm.SenderOptions.timestamp_format', index=3,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurement_delay_mode', full_name='srv6pm.SenderOptions.measurement_delay_mode', index=4,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='padding_mbz', full_name='srv6pm.SenderOptions.padding_mbz', index=5,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurement_loss_mode', full_name='srv6pm.SenderOptions.measurement_loss_mode', index=6,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authentication_key', full_name='srv6pm.SenderOptions.authentication_key', index=7,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=840,
)

_SRV6EPREPLYSENDER.fields_by_name['status'].enum_type = commons__pb2._STATUSCODE
_STARTEXPERIMENTSENDERREQUEST.fields_by_name['sender_options'].message_type = _SENDEROPTIONS
_STARTEXPERIMENTSENDERREPLY.fields_by_name['status'].enum_type = commons__pb2._STATUSCODE
_SENDEROPTIONS.fields_by_name['measurement_protocol'].enum_type = srv6pmCommons__pb2._MEASUREMENTPROTOCOL
_SENDEROPTIONS.fields_by_name['authentication_mode'].enum_type = srv6pmCommons__pb2._AUTHENTICATIONMODE
_SENDEROPTIONS.fields_by_name['measurement_type'].enum_type = srv6pmCommons__pb2._MEASUREMENTTYPE
_SENDEROPTIONS.fields_by_name['timestamp_format'].enum_type = srv6pmCommons__pb2._TIMESTAMPFORMAT
_SENDEROPTIONS.fields_by_name['measurement_delay_mode'].enum_type = srv6pmCommons__pb2._MEASUREMENTDELAYMODE
_SENDEROPTIONS.fields_by_name['measurement_loss_mode'].enum_type = srv6pmCommons__pb2._MEASUREMENTLOSSMODE
DESCRIPTOR.message_types_by_name['SRv6EPRequestSender'] = _SRV6EPREQUESTSENDER
DESCRIPTOR.message_types_by_name['SRv6EPReplySender'] = _SRV6EPREPLYSENDER
DESCRIPTOR.message_types_by_name['StartExperimentSenderRequest'] = _STARTEXPERIMENTSENDERREQUEST
DESCRIPTOR.message_types_by_name['StartExperimentSenderReply'] = _STARTEXPERIMENTSENDERREPLY
DESCRIPTOR.message_types_by_name['SenderOptions'] = _SENDEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SRv6EPRequestSender = _reflection.GeneratedProtocolMessageType('SRv6EPRequestSender', (_message.Message,), {
  'DESCRIPTOR' : _SRV6EPREQUESTSENDER,
  '__module__' : 'srv6pmSender_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.SRv6EPRequestSender)
  })
_sym_db.RegisterMessage(SRv6EPRequestSender)

SRv6EPReplySender = _reflection.GeneratedProtocolMessageType('SRv6EPReplySender', (_message.Message,), {
  'DESCRIPTOR' : _SRV6EPREPLYSENDER,
  '__module__' : 'srv6pmSender_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.SRv6EPReplySender)
  })
_sym_db.RegisterMessage(SRv6EPReplySender)

StartExperimentSenderRequest = _reflection.GeneratedProtocolMessageType('StartExperimentSenderRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTEXPERIMENTSENDERREQUEST,
  '__module__' : 'srv6pmSender_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.StartExperimentSenderRequest)
  })
_sym_db.RegisterMessage(StartExperimentSenderRequest)

StartExperimentSenderReply = _reflection.GeneratedProtocolMessageType('StartExperimentSenderReply', (_message.Message,), {
  'DESCRIPTOR' : _STARTEXPERIMENTSENDERREPLY,
  '__module__' : 'srv6pmSender_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.StartExperimentSenderReply)
  })
_sym_db.RegisterMessage(StartExperimentSenderReply)

SenderOptions = _reflection.GeneratedProtocolMessageType('SenderOptions', (_message.Message,), {
  'DESCRIPTOR' : _SENDEROPTIONS,
  '__module__' : 'srv6pmSender_pb2'
  # @@protoc_insertion_point(class_scope:srv6pm.SenderOptions)
  })
_sym_db.RegisterMessage(SenderOptions)



_SRV6PMSENDER = _descriptor.ServiceDescriptor(
  name='SRv6PMSender',
  full_name='srv6pm.SRv6PMSender',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=843,
  serialized_end=1132,
  methods=[
  _descriptor.MethodDescriptor(
    name='startExperiment',
    full_name='srv6pm.SRv6PMSender.startExperiment',
    index=0,
    containing_service=None,
    input_type=_STARTEXPERIMENTSENDERREQUEST,
    output_type=_STARTEXPERIMENTSENDERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopExperiment',
    full_name='srv6pm.SRv6PMSender.stopExperiment',
    index=1,
    containing_service=None,
    input_type=srv6pmCommons__pb2._STOPEXPERIMENTREQUEST,
    output_type=srv6pmCommons__pb2._STOPEXPERIMENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='retriveExperimentResults',
    full_name='srv6pm.SRv6PMSender.retriveExperimentResults',
    index=2,
    containing_service=None,
    input_type=srv6pmCommons__pb2._RETRIVEEXPERIMENTDATAREQUEST,
    output_type=srv6pmCommons__pb2._EXPERIMENTDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SRV6PMSENDER)

DESCRIPTOR.services_by_name['SRv6PMSender'] = _SRV6PMSENDER

# @@protoc_insertion_point(module_scope)
